unique_ids:
  forms:
    Form1: GIRVXXW64RHB5N7HNRO3NSUXMPLHWPU2
    Form1.ItemTemplate1: 7FCJ7V644BJBCT7XHOT6ZG7JJBLFPQDR
  modules: {}
  server_modules:
    ServerPackage1: F3PMYKBU733HZRJTCSZ5RYS3C2YVIGZP
  assets:
    standard-page.html: GLOEX6LBPY24WAHSO3IGMZTWA7DC6XWE
    theme.css: 7F46NYPR5JLGYI3TIF6W7TKMDLLS3LHE
